{{- if .Values.nodeAnalyzer.deploy }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "sysdig.fullname" . }}-host-analyzer
  labels:
{{ include "sysdig.labels" . | indent 4 }}
data:
  {{- if .Values.nodeAnalyzer.collectorEndpoint }}
  collector_endpoint: "https://{{ .Values.nodeImageAnalyzer.settings.collectorEndpoint }}/internal/scanning/scanning-analysis-collector"
  {{- end }}
  {{- if .Values.nodeAnalyzer.collectorTimeout }}
  collector_timeout: {{ .Values.nodeAnalyzer.collectorTimeout }}
  {{- end }}
  {{- if hasKey .Values.nodeAnalyzer "sslVerifyCertificate" }}
  ssl_verify_certificate: "{{ .Values.nodeAnalyzer.sslVerifyCertificate }}"
  {{- end }}

  debug: "{{ .Values.nodeAnalyzer.debug | default false }}"

  {{- if .Values.nodeAnalyzer.hostAnalyzer.settings.schedule }}
  schedule: {{ .Values.nodeAnalyzer.hostAnalyzer.settings.schedule }}
  {{- end }}
  {{- if .Values.nodeAnalyzer.hostAnalyzer.settings.analyzeAtStartup }}
  analyze_at_startup: {{ .Values.nodeAnalyzer.hostAnalyzer.settings.analyzeAtStartup }}
  {{- end }}
  {{- if .Values.nodeAnalyzer.hostAnalyzer.settings.hostBase }}
  host_base: {{ .Values.nodeAnalyzer.hostAnalyzer.settings.hostBase }}
  {{- end }}
  {{- if .Values.nodeAnalyzer.hostAnalyzer.settings.dirsToScan }}
  dirs_to_scan: {{ .Values.nodeAnalyzer.hostAnalyzer.settings.dirsToScan }}
  {{- end }}
  {{- if .Values.nodeAnalyzer.hostAnalyzer.settings.maxSendAttempts }}
  max_send_attempts: {{ .Values.nodeAnalyzer.hostAnalyzer.settings.maxSendAttempts }}
  {{- end }}

  {{- if .Values.nodeAnalyzer.httpProxy }}
  http_proxy: {{ .Values.nodeAnalyzer.httpProxy }}
  {{- end -}}
  {{- if .Values.nodeAnalyzer.httpsProxy }}
  https_proxy: {{ .Values.nodeAnalyzer.httpsProxy }}
  {{- end -}}
  {{- if .Values.nodeAnalyzer.noProxy }}
  no_proxy: {{ .Values.nodeAnalyzer.noProxy }}
  {{- end -}}
{{- end }}
